### ISSUE TITLE
KeyError: 'pages'

### ISSUE THREAD

**Issue by asgernim** [vishakraj25/Fraper#1]
I get a KeyError: 'pages' when I try to run guardian.py.

**Comment by vishakraj25** [comment]
Hello,

Sorry for very late responce

I checked the codes, working perfectly,

the key error : 'pages' which tells us the total pages we get for the call(each page has 10 News).

I checked the guardian responce has the parameter 'pages' in the JSON...

For example, I searched about "Trump", the result has 220443 pages, each page contains 10 News about Trump

![image](https://user-images.githubusercontent.com/33391433/87276090-3dc03c80-c4fd-11ea-8c2f-052a76cc420d.png)

If you have any doubts, I can help you:-)
